export interface Country {
  isoCountryCode: string;
  callingCode: string;
  flag: string;
  name: string;
}

const defaultCountryCodes: Country[] = [
  {
    isoCountryCode: "AD",
    callingCode: "376",
    flag: "🇦🇩",
    name: "Andorra",
  },
  {
    isoCountryCode: "AE",
    callingCode: "971",
    flag: "🇦🇪",
    name: "United Arab Emirates",
  },
  {
    isoCountryCode: "AF",
    callingCode: "93",
    flag: "🇦🇫",
    name: "Afghanistan",
  },
  {
    isoCountryCode: "AG",
    callingCode: "1",
    flag: "🇦🇬",
    name: "Antigua and Barbuda",
  },
  {
    isoCountryCode: "AI",
    callingCode: "1",
    flag: "🇦🇮",
    name: "Anguilla",
  },
  {
    isoCountryCode: "AL",
    callingCode: "355",
    flag: "🇦🇱",
    name: "Albania",
  },
  {
    isoCountryCode: "AM",
    callingCode: "374",
    flag: "🇦🇲",
    name: "Armenia",
  },
  {
    isoCountryCode: "AO",
    callingCode: "244",
    flag: "🇦🇴",
    name: "Angola",
  },
  {
    isoCountryCode: "AQ",
    callingCode: "672",
    flag: "🇦🇶",
    name: "Antarctica",
  },
  {
    isoCountryCode: "AR",
    callingCode: "54",
    flag: "🇦🇷",
    name: "Argentina",
  },
  {
    isoCountryCode: "AS",
    callingCode: "1",
    flag: "🇦🇸",
    name: "American Samoa",
  },
  {
    isoCountryCode: "AT",
    callingCode: "43",
    flag: "🇦🇹",
    name: "Austria",
  },
  {
    isoCountryCode: "AU",
    callingCode: "61",
    flag: "🇦🇺",
    name: "Australia",
  },
  {
    isoCountryCode: "AW",
    callingCode: "297",
    flag: "🇦🇼",
    name: "Aruba",
  },
  {
    isoCountryCode: "AX",
    callingCode: "358",
    flag: "🇦🇽",
    name: "Åland Islands",
  },
  {
    isoCountryCode: "AZ",
    callingCode: "994",
    flag: "🇦🇿",
    name: "Azerbaijan",
  },
  {
    isoCountryCode: "BA",
    callingCode: "387",
    flag: "🇧🇦",
    name: "Bosnia and Herzegovina",
  },
  {
    isoCountryCode: "BB",
    callingCode: "1",
    flag: "🇧🇧",
    name: "Barbados",
  },
  {
    isoCountryCode: "BD",
    callingCode: "880",
    flag: "🇧🇩",
    name: "Bangladesh",
  },
  {
    isoCountryCode: "BE",
    callingCode: "32",
    flag: "🇧🇪",
    name: "Belgium",
  },
  {
    isoCountryCode: "BF",
    callingCode: "226",
    flag: "🇧🇫",
    name: "Burkina Faso",
  },
  {
    isoCountryCode: "BG",
    callingCode: "359",
    flag: "🇧🇬",
    name: "Bulgaria",
  },
  {
    isoCountryCode: "BH",
    callingCode: "973",
    flag: "🇧🇭",
    name: "Bahrain",
  },
  {
    isoCountryCode: "BI",
    callingCode: "257",
    flag: "🇧🇮",
    name: "Burundi",
  },
  {
    isoCountryCode: "BJ",
    callingCode: "229",
    flag: "🇧🇯",
    name: "Benin",
  },
  {
    isoCountryCode: "BL",
    callingCode: "590",
    flag: "🇧🇱",
    name: "Saint Barthélemy",
  },
  {
    isoCountryCode: "BM",
    callingCode: "1",
    flag: "🇧🇲",
    name: "Bermuda",
  },
  {
    isoCountryCode: "BN",
    callingCode: "673",
    flag: "🇧🇳",
    name: "Brunei Darussalam",
  },
  {
    isoCountryCode: "BO",
    callingCode: "591",
    flag: "🇧🇴",
    name: "Bolivia",
  },
  {
    isoCountryCode: "BQ",
    callingCode: "599",
    flag: "🇧🇶",
    name: "Bonaire, Sint Eustatius and Saba",
  },
  {
    isoCountryCode: "BR",
    callingCode: "55",
    flag: "🇧🇷",
    name: "Brazil",
  },
  {
    isoCountryCode: "BS",
    callingCode: "1",
    flag: "🇧🇸",
    name: "Bahamas",
  },
  {
    isoCountryCode: "BT",
    callingCode: "975",
    flag: "🇧🇹",
    name: "Bhutan",
  },
  {
    isoCountryCode: "BW",
    callingCode: "267",
    flag: "🇧🇼",
    name: "Botswana",
  },
  {
    isoCountryCode: "BY",
    callingCode: "375",
    flag: "🇧🇾",
    name: "Belarus",
  },
  {
    isoCountryCode: "BZ",
    callingCode: "501",
    flag: "🇧🇿",
    name: "Belize",
  },
  {
    isoCountryCode: "CA",
    callingCode: "1",
    flag: "🇨🇦",
    name: "Canada",
  },
  {
    isoCountryCode: "CC",
    callingCode: "891",
    flag: "🇨🇨",
    name: "Cocos (Keeling) Islands",
  },
  {
    isoCountryCode: "CD",
    callingCode: "243",
    flag: "🇨🇩",
    name: "Congo",
  },
  {
    isoCountryCode: "CF",
    callingCode: "236",
    flag: "🇨🇫",
    name: "Central African Republic",
  },
  {
    isoCountryCode: "CG",
    callingCode: "242",
    flag: "🇨🇬",
    name: "Congo",
  },
  {
    isoCountryCode: "CH",
    callingCode: "41",
    flag: "🇨🇭",
    name: "Switzerland",
  },
  {
    isoCountryCode: "CI",
    callingCode: "225",
    flag: "🇨🇮",
    name: "Côte D'Ivoire",
  },
  {
    isoCountryCode: "CK",
    callingCode: "682",
    flag: "🇨🇰",
    name: "Cook Islands",
  },
  {
    isoCountryCode: "CL",
    callingCode: "56",
    flag: "🇨🇱",
    name: "Chile",
  },
  {
    isoCountryCode: "CM",
    callingCode: "237",
    flag: "🇨🇲",
    name: "Cameroon",
  },
  {
    isoCountryCode: "CN",
    callingCode: "86",
    flag: "🇨🇳",
    name: "China",
  },
  {
    isoCountryCode: "CO",
    callingCode: "57",
    flag: "🇨🇴",
    name: "Colombia",
  },
  {
    isoCountryCode: "CR",
    callingCode: "506",
    flag: "🇨🇷",
    name: "Costa Rica",
  },
  {
    isoCountryCode: "CU",
    callingCode: "53",
    flag: "🇨🇺",
    name: "Cuba",
  },
  {
    isoCountryCode: "CV",
    callingCode: "238",
    flag: "🇨🇻",
    name: "Cape Verde",
  },
  {
    isoCountryCode: "CW",
    callingCode: "599",
    flag: "🇨🇼",
    name: "Curaçao",
  },
  {
    isoCountryCode: "CX",
    callingCode: "61",
    flag: "🇨🇽",
    name: "Christmas Island",
  },
  {
    isoCountryCode: "CY",
    callingCode: "357",
    flag: "🇨🇾",
    name: "Cyprus",
  },
  {
    isoCountryCode: "CZ",
    callingCode: "420",
    flag: "🇨🇿",
    name: "Czech Republic",
  },
  {
    isoCountryCode: "DE",
    callingCode: "49",
    flag: "🇩🇪",
    name: "Germany",
  },
  {
    isoCountryCode: "DJ",
    callingCode: "253",
    flag: "🇩🇯",
    name: "Djibouti",
  },
  {
    isoCountryCode: "DK",
    callingCode: "45",
    flag: "🇩🇰",
    name: "Denmark",
  },
  {
    isoCountryCode: "DM",
    callingCode: "1",
    flag: "🇩🇲",
    name: "Dominica",
  },
  {
    isoCountryCode: "DO",
    callingCode: "1",
    flag: "🇩🇴",
    name: "Dominican Republic",
  },
  {
    isoCountryCode: "DZ",
    callingCode: "213",
    flag: "🇩🇿",
    name: "Algeria",
  },
  {
    isoCountryCode: "EC",
    callingCode: "593",
    flag: "🇪🇨",
    name: "Ecuador",
  },
  {
    isoCountryCode: "EE",
    callingCode: "372",
    flag: "🇪🇪",
    name: "Estonia",
  },
  {
    isoCountryCode: "EG",
    callingCode: "20",
    flag: "🇪🇬",
    name: "Egypt",
  },
  {
    isoCountryCode: "EH",
    callingCode: "212",
    flag: "🇪🇭",
    name: "Western Sahara",
  },
  {
    isoCountryCode: "ER",
    callingCode: "291",
    flag: "🇪🇷",
    name: "Eritrea",
  },
  {
    isoCountryCode: "ES",
    callingCode: "34",
    flag: "🇪🇸",
    name: "Spain",
  },
  {
    isoCountryCode: "ET",
    callingCode: "251",
    flag: "🇪🇹",
    name: "Ethiopia",
  },
  {
    isoCountryCode: "FI",
    callingCode: "358",
    flag: "🇫🇮",
    name: "Finland",
  },
  {
    isoCountryCode: "FJ",
    callingCode: "679",
    flag: "🇫🇯",
    name: "Fiji",
  },
  {
    isoCountryCode: "FK",
    callingCode: "500",
    flag: "🇫🇰",
    name: "Falkland Islands (Malvinas)",
  },
  {
    isoCountryCode: "FM",
    callingCode: "691",
    flag: "🇫🇲",
    name: "Micronesia",
  },
  {
    isoCountryCode: "FO",
    callingCode: "298",
    flag: "🇫🇴",
    name: "Faroe Islands",
  },
  {
    isoCountryCode: "FR",
    callingCode: "33",
    flag: "🇫🇷",
    name: "France",
  },
  {
    isoCountryCode: "GA",
    callingCode: "241",
    flag: "🇬🇦",
    name: "Gabon",
  },
  {
    isoCountryCode: "GB",
    callingCode: "44",
    flag: "🇬🇧",
    name: "United Kingdom",
  },
  {
    isoCountryCode: "GD",
    callingCode: "1",
    flag: "🇬🇩",
    name: "Grenada",
  },
  {
    isoCountryCode: "GE",
    callingCode: "995",
    flag: "🇬🇪",
    name: "Georgia",
  },
  {
    isoCountryCode: "GF",
    callingCode: "594",
    flag: "🇬🇫",
    name: "French Guiana",
  },
  {
    isoCountryCode: "GG",
    callingCode: "44",
    flag: "🇬🇬",
    name: "Guernsey",
  },
  {
    isoCountryCode: "GH",
    callingCode: "233",
    flag: "🇬🇭",
    name: "Ghana",
  },
  {
    isoCountryCode: "GI",
    callingCode: "350",
    flag: "🇬🇮",
    name: "Gibraltar",
  },
  {
    isoCountryCode: "GL",
    callingCode: "299",
    flag: "🇬🇱",
    name: "Greenland",
  },
  {
    isoCountryCode: "GM",
    callingCode: "220",
    flag: "🇬🇲",
    name: "Gambia",
  },
  {
    isoCountryCode: "GN",
    callingCode: "224",
    flag: "🇬🇳",
    name: "Guinea",
  },
  {
    isoCountryCode: "GP",
    callingCode: "590",
    flag: "🇬🇵",
    name: "Guadeloupe",
  },
  {
    isoCountryCode: "GQ",
    callingCode: "240",
    flag: "🇬🇶",
    name: "Equatorial Guinea",
  },
  {
    isoCountryCode: "GR",
    callingCode: "30",
    flag: "🇬🇷",
    name: "Greece",
  },
  {
    isoCountryCode: "GS",
    callingCode: "995",
    flag: "🇬🇸",
    name: "South Georgia",
  },
  {
    isoCountryCode: "GT",
    callingCode: "502",
    flag: "🇬🇹",
    name: "Guatemala",
  },
  {
    isoCountryCode: "GU",
    callingCode: "1-671",
    flag: "🇬🇺",
    name: "Guam",
  },
  {
    isoCountryCode: "GW",
    callingCode: "245",
    flag: "🇬🇼",
    name: "Guinea-Bissau",
  },
  {
    isoCountryCode: "GY",
    callingCode: "592",
    flag: "🇬🇾",
    name: "Guyana",
  },
  {
    isoCountryCode: "HK",
    callingCode: "852",
    flag: "🇭🇰",
    name: "Hong Kong",
  },
  {
    isoCountryCode: "HN",
    callingCode: "504",
    flag: "🇭🇳",
    name: "Honduras",
  },
  {
    isoCountryCode: "HR",
    callingCode: "385",
    flag: "🇭🇷",
    name: "Croatia",
  },
  {
    isoCountryCode: "HT",
    callingCode: "509",
    flag: "🇭🇹",
    name: "Haiti",
  },
  {
    isoCountryCode: "HU",
    callingCode: "36",
    flag: "🇭🇺",
    name: "Hungary",
  },
  {
    isoCountryCode: "isoCountryCode",
    callingCode: "62",
    flag: "🇮🇩",
    name: "Indonesia",
  },
  {
    isoCountryCode: "IE",
    callingCode: "353",
    flag: "🇮🇪",
    name: "Ireland",
  },
  {
    isoCountryCode: "IL",
    callingCode: "972",
    flag: "🇮🇱",
    name: "Israel",
  },
  {
    isoCountryCode: "IM",
    callingCode: "44",
    flag: "🇮🇲",
    name: "Isle of Man",
  },
  {
    isoCountryCode: "IN",
    callingCode: "91",
    flag: "🇮🇳",
    name: "India",
  },
  {
    isoCountryCode: "IO",
    callingCode: "246",
    flag: "🇮🇴",
    name: "British Indian Ocean Territory",
  },
  {
    isoCountryCode: "IQ",
    callingCode: "964",
    flag: "🇮🇶",
    name: "Iraq",
  },
  {
    isoCountryCode: "IR",
    callingCode: "98",
    flag: "🇮🇷",
    name: "Iran",
  },
  {
    isoCountryCode: "IS",
    callingCode: "354",
    flag: "🇮🇸",
    name: "Iceland",
  },
  {
    isoCountryCode: "IT",
    callingCode: "39",
    flag: "🇮🇹",
    name: "Italy",
  },
  {
    isoCountryCode: "JE",
    callingCode: "44",
    flag: "🇯🇪",
    name: "Jersey",
  },
  {
    isoCountryCode: "JM",
    callingCode: "1",
    flag: "🇯🇲",
    name: "Jamaica",
  },
  {
    isoCountryCode: "JO",
    callingCode: "962",
    flag: "🇯🇴",
    name: "Jordan",
  },
  {
    isoCountryCode: "JP",
    callingCode: "81",
    flag: "🇯🇵",
    name: "Japan",
  },
  {
    isoCountryCode: "KE",
    callingCode: "254",
    flag: "🇰🇪",
    name: "Kenya",
  },
  {
    isoCountryCode: "KG",
    callingCode: "996",
    flag: "🇰🇬",
    name: "Kyrgyzstan",
  },
  {
    isoCountryCode: "KH",
    callingCode: "855",
    flag: "🇰🇭",
    name: "Cambodia",
  },
  {
    isoCountryCode: "KI",
    callingCode: "686",
    flag: "🇰🇮",
    name: "Kiribati",
  },
  {
    isoCountryCode: "KM",
    callingCode: "269",
    flag: "🇰🇲",
    name: "Comoros",
  },
  {
    isoCountryCode: "KN",
    callingCode: "1",
    flag: "🇰🇳",
    name: "Saint Kitts and Nevis",
  },
  {
    isoCountryCode: "KP",
    callingCode: "850",
    flag: "🇰🇵",
    name: "North Korea",
  },
  {
    isoCountryCode: "KR",
    callingCode: "82",
    flag: "🇰🇷",
    name: "South Korea",
  },
  {
    isoCountryCode: "KW",
    callingCode: "965",
    flag: "🇰🇼",
    name: "Kuwait",
  },
  {
    isoCountryCode: "KY",
    callingCode: "1",
    flag: "🇰🇾",
    name: "Cayman Islands",
  },
  {
    isoCountryCode: "KZ",
    callingCode: "7",
    flag: "🇰🇿",
    name: "Kazakhstan",
  },
  {
    isoCountryCode: "LA",
    callingCode: "856",
    flag: "🇱🇦",
    name: "Lao People's Democratic Republic",
  },
  {
    isoCountryCode: "LB",
    callingCode: "961",
    flag: "🇱🇧",
    name: "Lebanon",
  },
  {
    isoCountryCode: "LC",
    callingCode: "1",
    flag: "🇱🇨",
    name: "Saint Lucia",
  },
  {
    isoCountryCode: "LI",
    callingCode: "423",
    flag: "🇱🇮",
    name: "Liechtenstein",
  },
  {
    isoCountryCode: "LK",
    callingCode: "94",
    flag: "🇱🇰",
    name: "Sri Lanka",
  },
  {
    isoCountryCode: "LR",
    callingCode: "231",
    flag: "🇱🇷",
    name: "Liberia",
  },
  {
    isoCountryCode: "LS",
    callingCode: "266",
    flag: "🇱🇸",
    name: "Lesotho",
  },
  {
    isoCountryCode: "LT",
    callingCode: "370",
    flag: "🇱🇹",
    name: "Lithuania",
  },
  {
    isoCountryCode: "LU",
    callingCode: "352",
    flag: "🇱🇺",
    name: "Luxembourg",
  },
  {
    isoCountryCode: "LV",
    callingCode: "371",
    flag: "🇱🇻",
    name: "Latvia",
  },
  {
    isoCountryCode: "LY",
    callingCode: "218",
    flag: "🇱🇾",
    name: "Libya",
  },
  {
    isoCountryCode: "MA",
    callingCode: "212",
    flag: "🇲🇦",
    name: "Morocco",
  },
  {
    isoCountryCode: "MC",
    callingCode: "377",
    flag: "🇲🇨",
    name: "Monaco",
  },
  {
    isoCountryCode: "MD",
    callingCode: "373",
    flag: "🇲🇩",
    name: "Moldova",
  },
  {
    isoCountryCode: "ME",
    callingCode: "382",
    flag: "🇲🇪",
    name: "Montenegro",
  },
  {
    isoCountryCode: "MF",
    callingCode: "590",
    flag: "🇲🇫",
    name: "Saint Martin (French Part)",
  },
  {
    isoCountryCode: "MG",
    callingCode: "261",
    flag: "🇲🇬",
    name: "Madagascar",
  },
  {
    isoCountryCode: "MH",
    callingCode: "692",
    flag: "🇲🇭",
    name: "Marshall Islands",
  },
  {
    isoCountryCode: "MK",
    callingCode: "389",
    flag: "🇲🇰",
    name: "Macedonia",
  },
  {
    isoCountryCode: "ML",
    callingCode: "223",
    flag: "🇲🇱",
    name: "Mali",
  },
  {
    isoCountryCode: "MM",
    callingCode: "95",
    flag: "🇲🇲",
    name: "Myanmar",
  },
  {
    isoCountryCode: "MN",
    callingCode: "976",
    flag: "🇲🇳",
    name: "Mongolia",
  },
  {
    isoCountryCode: "MO",
    callingCode: "853",
    flag: "🇲🇴",
    name: "Macao",
  },
  {
    isoCountryCode: "MP",
    callingCode: "1",
    flag: "🇲🇵",
    name: "Northern Mariana Islands",
  },
  {
    isoCountryCode: "MQ",
    callingCode: "596",
    flag: "🇲🇶",
    name: "Martinique",
  },
  {
    isoCountryCode: "MR",
    callingCode: "222",
    flag: "🇲🇷",
    name: "Mauritania",
  },
  {
    isoCountryCode: "MS",
    callingCode: "1",
    flag: "🇲🇸",
    name: "Montserrat",
  },
  {
    isoCountryCode: "MT",
    callingCode: "356",
    flag: "🇲🇹",
    name: "Malta",
  },
  {
    isoCountryCode: "MU",
    callingCode: "230",
    flag: "🇲🇺",
    name: "Mauritius",
  },
  {
    isoCountryCode: "MV",
    callingCode: "960",
    flag: "🇲🇻",
    name: "Maldives",
  },
  {
    isoCountryCode: "MW",
    callingCode: "265",
    flag: "🇲🇼",
    name: "Malawi",
  },
  {
    isoCountryCode: "MX",
    callingCode: "52",
    flag: "🇲🇽",
    name: "Mexico",
  },
  {
    isoCountryCode: "MY",
    callingCode: "60",
    flag: "🇲🇾",
    name: "Malaysia",
  },
  {
    isoCountryCode: "MZ",
    callingCode: "258",
    flag: "🇲🇿",
    name: "Mozambique",
  },
  {
    isoCountryCode: "NA",
    callingCode: "264",
    flag: "🇳🇦",
    name: "Namibia",
  },
  {
    isoCountryCode: "NC",
    callingCode: "687",
    flag: "🇳🇨",
    name: "New Caledonia",
  },
  {
    isoCountryCode: "NE",
    callingCode: "227",
    flag: "🇳🇪",
    name: "Niger",
  },
  {
    isoCountryCode: "NF",
    callingCode: "672",
    flag: "🇳🇫",
    name: "Norfolk Island",
  },
  {
    isoCountryCode: "NG",
    callingCode: "234",
    flag: "🇳🇬",
    name: "Nigeria",
  },
  {
    isoCountryCode: "NI",
    callingCode: "505",
    flag: "🇳🇮",
    name: "Nicaragua",
  },
  {
    isoCountryCode: "NL",
    callingCode: "31",
    flag: "🇳🇱",
    name: "Netherlands",
  },
  {
    isoCountryCode: "NO",
    callingCode: "47",
    flag: "🇳🇴",
    name: "Norway",
  },
  {
    isoCountryCode: "NP",
    callingCode: "977",
    flag: "🇳🇵",
    name: "Nepal",
  },
  {
    isoCountryCode: "NR",
    callingCode: "674",
    flag: "🇳🇷",
    name: "Nauru",
  },
  {
    isoCountryCode: "NU",
    callingCode: "683",
    flag: "🇳🇺",
    name: "Niue",
  },
  {
    isoCountryCode: "NZ",
    callingCode: "64",
    flag: "🇳🇿",
    name: "New Zealand",
  },
  {
    isoCountryCode: "OM",
    callingCode: "968",
    flag: "🇴🇲",
    name: "Oman",
  },
  {
    isoCountryCode: "PA",
    callingCode: "507",
    flag: "🇵🇦",
    name: "Panama",
  },
  {
    isoCountryCode: "PE",
    callingCode: "51",
    flag: "🇵🇪",
    name: "Peru",
  },
  {
    isoCountryCode: "PF",
    callingCode: "689",
    flag: "🇵🇫",
    name: "French Polynesia",
  },
  {
    isoCountryCode: "PG",
    callingCode: "675",
    flag: "🇵🇬",
    name: "Papua New Guinea",
  },
  {
    isoCountryCode: "PH",
    callingCode: "63",
    flag: "🇵🇭",
    name: "Philippines",
  },
  {
    isoCountryCode: "PK",
    callingCode: "92",
    flag: "🇵🇰",
    name: "Pakistan",
  },
  {
    isoCountryCode: "PL",
    callingCode: "48",
    flag: "🇵🇱",
    name: "Poland",
  },
  {
    isoCountryCode: "PM",
    callingCode: "508",
    flag: "🇵🇲",
    name: "Saint Pierre and Miquelon",
  },
  {
    isoCountryCode: "PN",
    callingCode: "64",
    flag: "🇵🇳",
    name: "Pitcairn",
  },
  {
    isoCountryCode: "PR",
    callingCode: "1-787, 1-939",
    flag: "🇵🇷",
    name: "Puerto Rico",
  },
  {
    isoCountryCode: "PS",
    callingCode: "970",
    flag: "🇵🇸",
    name: "Palestinian Territory",
  },
  {
    isoCountryCode: "PT",
    callingCode: "351",
    flag: "🇵🇹",
    name: "Portugal",
  },
  {
    isoCountryCode: "PW",
    callingCode: "680",
    flag: "🇵🇼",
    name: "Palau",
  },
  {
    isoCountryCode: "PY",
    callingCode: "595",
    flag: "🇵🇾",
    name: "Paraguay",
  },
  {
    isoCountryCode: "QA",
    callingCode: "974",
    flag: "🇶🇦",
    name: "Qatar",
  },
  {
    isoCountryCode: "RE",
    callingCode: "262",
    flag: "🇷🇪",
    name: "Réunion",
  },
  {
    isoCountryCode: "RO",
    callingCode: "40",
    flag: "🇷🇴",
    name: "Romania",
  },
  {
    isoCountryCode: "RS",
    callingCode: "381",
    flag: "🇷🇸",
    name: "Serbia",
  },
  {
    isoCountryCode: "RU",
    callingCode: "7",
    flag: "🇷🇺",
    name: "Russia",
  },
  {
    isoCountryCode: "RW",
    callingCode: "250",
    flag: "🇷🇼",
    name: "Rwanda",
  },
  {
    isoCountryCode: "SA",
    callingCode: "966",
    flag: "🇸🇦",
    name: "Saudi Arabia",
  },
  {
    isoCountryCode: "SB",
    callingCode: "677",
    flag: "🇸🇧",
    name: "Solomon Islands",
  },
  {
    isoCountryCode: "SC",
    callingCode: "248",
    flag: "🇸🇨",
    name: "Seychelles",
  },
  {
    isoCountryCode: "SD",
    callingCode: "249",
    flag: "🇸🇩",
    name: "Sudan",
  },
  {
    isoCountryCode: "SE",
    callingCode: "46",
    flag: "🇸🇪",
    name: "Sweden",
  },
  {
    isoCountryCode: "SG",
    callingCode: "65",
    flag: "🇸🇬",
    name: "Singapore",
  },
  {
    isoCountryCode: "SH",
    callingCode: "290",
    flag: "🇸🇭",
    name: "Saint Helena, Ascension and Tristan Da Cunha",
  },
  {
    isoCountryCode: "SI",
    callingCode: "386",
    flag: "🇸🇮",
    name: "Slovenia",
  },
  {
    isoCountryCode: "SJ",
    callingCode: "47",
    flag: "🇸🇯",
    name: "Svalbard and Jan Mayen",
  },
  {
    isoCountryCode: "SK",
    callingCode: "421",
    flag: "🇸🇰",
    name: "Slovakia",
  },
  {
    isoCountryCode: "SL",
    callingCode: "232",
    flag: "🇸🇱",
    name: "Sierra Leone",
  },
  {
    isoCountryCode: "SM",
    callingCode: "378",
    flag: "🇸🇲",
    name: "San Marino",
  },
  {
    isoCountryCode: "SN",
    callingCode: "221",
    flag: "🇸🇳",
    name: "Senegal",
  },
  {
    isoCountryCode: "SO",
    callingCode: "252",
    flag: "🇸🇴",
    name: "Somalia",
  },
  {
    isoCountryCode: "SR",
    callingCode: "597",
    flag: "🇸🇷",
    name: "Suriname",
  },
  {
    isoCountryCode: "SS",
    callingCode: "211",
    flag: "🇸🇸",
    name: "South Sudan",
  },
  {
    isoCountryCode: "ST",
    callingCode: "239",
    flag: "🇸🇹",
    name: "Sao Tome and Principe",
  },
  {
    isoCountryCode: "SV",
    callingCode: "503",
    flag: "🇸🇻",
    name: "El Salvador",
  },
  {
    isoCountryCode: "SX",
    callingCode: "1",
    flag: "🇸🇽",
    name: "Sint Maarten (Dutch Part)",
  },
  {
    isoCountryCode: "SY",
    callingCode: "963",
    flag: "🇸🇾",
    name: "Syrian Arab Republic",
  },
  {
    isoCountryCode: "SZ",
    callingCode: "268",
    flag: "🇸🇿",
    name: "Swaziland",
  },
  {
    isoCountryCode: "TC",
    callingCode: "1",
    flag: "🇹🇨",
    name: "Turks and Caicos Islands",
  },
  {
    isoCountryCode: "TD",
    callingCode: "235",
    flag: "🇹🇩",
    name: "Chad",
  },
  {
    isoCountryCode: "TG",
    callingCode: "228",
    flag: "🇹🇬",
    name: "Togo",
  },
  {
    isoCountryCode: "TH",
    callingCode: "66",
    flag: "🇹🇭",
    name: "Thailand",
  },
  {
    isoCountryCode: "TJ",
    callingCode: "992",
    flag: "🇹🇯",
    name: "Tajikistan",
  },
  {
    isoCountryCode: "TK",
    callingCode: "690",
    flag: "🇹🇰",
    name: "Tokelau",
  },
  {
    isoCountryCode: "TL",
    callingCode: "670",
    flag: "🇹🇱",
    name: "Timor-Leste",
  },
  {
    isoCountryCode: "TM",
    callingCode: "993",
    flag: "🇹🇲",
    name: "Turkmenistan",
  },
  {
    isoCountryCode: "TN",
    callingCode: "216",
    flag: "🇹🇳",
    name: "Tunisia",
  },
  {
    isoCountryCode: "TO",
    callingCode: "676",
    flag: "🇹🇴",
    name: "Tonga",
  },
  {
    isoCountryCode: "TR",
    callingCode: "90",
    flag: "🇹🇷",
    name: "Turkey",
  },
  {
    isoCountryCode: "TT",
    callingCode: "1",
    flag: "🇹🇹",
    name: "TrinisoCountryCodead and Tobago",
  },
  {
    isoCountryCode: "TV",
    callingCode: "688",
    flag: "🇹🇻",
    name: "Tuvalu",
  },
  {
    isoCountryCode: "TW",
    callingCode: "886",
    flag: "🇹🇼",
    name: "Taiwan",
  },
  {
    isoCountryCode: "TZ",
    callingCode: "255",
    flag: "🇹🇿",
    name: "Tanzania",
  },
  {
    isoCountryCode: "UA",
    callingCode: "380",
    flag: "🇺🇦",
    name: "Ukraine",
  },
  {
    isoCountryCode: "UG",
    callingCode: "256",
    flag: "🇺🇬",
    name: "Uganda",
  },
  {
    isoCountryCode: "UM",
    callingCode: "246",
    flag: "🇺🇲",
    name: "United States Minor Outlying Islands",
  },
  {
    isoCountryCode: "US",
    callingCode: "1",
    flag: "🇺🇸",
    name: "United States",
  },
  {
    isoCountryCode: "UY",
    callingCode: "598",
    flag: "🇺🇾",
    name: "Uruguay",
  },
  {
    isoCountryCode: "UZ",
    callingCode: "998",
    flag: "🇺🇿",
    name: "Uzbekistan",
  },
  {
    isoCountryCode: "VA",
    callingCode: "379",
    flag: "🇻🇦",
    name: "Vatican City",
  },
  {
    isoCountryCode: "VC",
    callingCode: "1",
    flag: "🇻🇨",
    name: "Saint Vincent and The Grenadines",
  },
  {
    isoCountryCode: "VE",
    callingCode: "58",
    flag: "🇻🇪",
    name: "Venezuela",
  },
  {
    isoCountryCode: "VG",
    callingCode: "1",
    flag: "🇻🇬",
    name: "Virgin Islands, British",
  },
  {
    isoCountryCode: "VI",
    callingCode: "1",
    flag: "🇻🇮",
    name: "Virgin Islands, U.S.",
  },
  {
    isoCountryCode: "VN",
    callingCode: "84",
    flag: "🇻🇳",
    name: "Viet Nam",
  },
  {
    isoCountryCode: "VU",
    callingCode: "678",
    flag: "🇻🇺",
    name: "Vanuatu",
  },
  {
    isoCountryCode: "WF",
    callingCode: "681",
    flag: "🇼🇫",
    name: "Wallis and Futuna",
  },
  {
    isoCountryCode: "WS",
    callingCode: "685",
    flag: "🇼🇸",
    name: "Samoa",
  },
  {
    isoCountryCode: "YE",
    callingCode: "967",
    flag: "🇾🇪",
    name: "Yemen",
  },
  {
    isoCountryCode: "YT",
    callingCode: "262",
    flag: "🇾🇹",
    name: "Mayotte",
  },
  {
    isoCountryCode: "ZA",
    callingCode: "27",
    flag: "🇿🇦",
    name: "South Africa",
  },
  {
    isoCountryCode: "ZM",
    callingCode: "260",
    flag: "🇿🇲",
    name: "Zambia",
  },
  {
    isoCountryCode: "ZW",
    callingCode: "263",
    flag: "🇿🇼",
    name: "Zimbabwe",
  },
];
export default defaultCountryCodes;
